### ISSUE TITLE
请问有考虑支持Vmess和Trojan的HTTP/2吗

### ISSUE THREAD

**Issue by Apocalypsor** [surgioproject/surgio#122]
Clash 已经均支持，见[文档](https://github.com/Dreamacro/clash/wiki/configuration#user-content-all-configuration-options:~:text=%2D%20name%3A%20%22vmess%2Dh2%22)

配置示例如下：
```
# vmess
- name: "vmess-h2"
  type: vmess
  server: server
  port: 443
  uuid: uuid
  alterId: 32
  cipher: auto
  network: h2
  tls: true
  h2-opts:
    host:
      - http.example.com
      - http-alt.example.com
    path: /

# Trojan
- name: "trojan"
  type: trojan
  server: server
  port: 443
  password: yourpsk
  # udp: true
  # sni: example.com # aka server name
  # alpn:
  #   - h2
  #   - http/1.1
  # skip-cert-verify: true
```
