### ISSUE TITLE
template中使用getClashNodeNames时出现缩进错误

### ISSUE THREAD

**Issue by xkww3n** [surgioproject/surgio#202]
在template中填写以下内容：
```
proxy-groups:
- type: select
  name: Proxy
  proxies: 
    - HK
    - TW
    - US
    - JP
    {{ getClashNodeNames(nodeList) | yaml }}
```
预期生成的内容应当是所有Clash节点条目具有相同的缩进：
```
proxy-groups:
- type: select
  name: Proxy
  proxies: 
    - HK
    - TW
    - US
    - JP
    - 节点1
    - 节点2
    - 节点3
```
但实际上只有“节点1”条目会有缩进，剩下的条目将不会缩进：
```
proxy-groups:
- type: select
  name: Proxy
  proxies: 
    - HK
    - TW
    - US
    - JP
    - 节点1
- 节点2
- 节点3
```
这样的配置文件将不会被代理软件所接受。
