### ISSUE TITLE
gitlab-ci 运行错误

### ISSUE THREAD

**Issue by 2PoL** [surgioproject/surgio#207]
.gitlab-ci.yml
``` 
image: node:10-stretch

before_script:
  - 'npm install --production'

stages:
  - build

build:
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - dist/
  only:
    - web # 能够在网页上触发
    - triggers # 能够通过 API 触发
    - schedules # 能够定时触发
  script:
    - npm run update
```
CI Job log
```
      npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-surgio@0.1.0 update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-03T03_28_31_300Z-debug.log
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 1
```
