### ISSUE TITLE
When some nodes discards as client not supported, they still appears in getNodeNames() method

### ISSUE THREAD

**Issue by RulesW** [surgioproject/surgio#214]
When I tried to generate Surge config, I found that while some nodes been discards since client not supported, they still appears in `getNodeNames()` method.
For example:
> node in clash format
```yaml
  - name: test1
    type: ss
    server: example.com
    port: 2333
    cipher:  chacha20-ietf-poly1305
    password: "password"
    plugin: v2ray-plugin
    plugin-opts:
      mode: websocket
      tls: false
      host: example.com
      path: "/example/path"
      mux: true
```
> Surgio format node
```javascript
{
  type: 'shadowsocks',
  nodeName: 'test1',
  hostname: 'example.com',
  port: 2333,
  method: 'chacha20-ietf-poly1305',
  password: 'password',
  'udp-relay': true,
  obfs: 'ws',
  'obfs-host': 'example.com',
  'obfs-uri': '/example/path',
  wsHeaders: {},
  mux: true
}
```

`getSurgeNodes()` discard this node, however `getNodeNames()` still got this node.

---
生成 surge 配置文件过程中，某些节点由于是ss的v2ray plugin，surge不支持此类型而被抛弃，但在`getNodeNames`内仍然存在导致surge报错。
